### PURPOSE: Check for mismatches in phenotype and genotype data for F50-56

### working dir for Natalia's clone of LgSm-DataProcessing repo
setwd("C:/Users/Administrator/Desktop/Scripts/LgSm-DataProcessing")

### LOAD DATA ------------------------------------------------------------------
### geno.samples is genotyped samples, info is phenotype data with fam info
### ail.kinship is a matrix of kinship coeffs from the pedigree,and grm is the
### IBS/grm for all genotyped samples.

# genotyped samples: add 0.1 to ID numbers so that they match ped IDs. these
# are the same animals - we added 0.1 to all IDs in F33 and beyond (this is
# when the palmer lab obtained the AIL) to avoid duplicate ID tags from Jim
# Cheverud's F2-32 mice.
# geno.samples <- read.table("./genotyped.samples.txt",as.is=T)
# names(geno.samples) <- c("id")
# geno.samples$id <- as.numeric(geno.samples$id)
# geno.samples$id <- geno.samples$id + 0.1

# all phenotype and covariate data - for CC, generation, sire/dam info. the
# ped file, pedforQTLrel.txt, should have some of this information as well, but
# it's useful to (a) check for concordance between my pheno data and ped data
# (ped data was generated automatically from AI Line Info_ files) and (b) fill
# in missing info for samples listed only in one file, if they exist.
# This is a large file and I only need the first few columns.

# info <- read.table("./dataFiles/phenotypes/allData.txt", sep="\t",
#                    header=T, as.is=T)[1:13]
# info <- info[,c(1,2,5,6,13)]
# info$id <- info$id + 0.1 # change IDs to match ped
# info$sex <- as.factor(info$sex)
# levels(info$sex) <- c(2, 1) # F=2 and M=1 (plink coding, for the # X chrs)

# the pheno data has an extra entry, 46368. He was phenotyped but most of his
# phenotypes were discounted because the locomotor data I collected from him
# was messed up. He's still listed in the complete pheno data set, though, so I
# have to remove him before dealing with the genotype and kinship data.

# which(!info$id %in% row.names(ail.kinship)) # 89, 46368, gen 50
# info <- info[c(1:88, 90:1124),]
# save(info, file="./pedigree/info.phenoSamples.RData")

## FYI, this is how kinship coeffs were generated from the pedigree
# library(QTLRel)
# ail.ped <- read.table("./pedigree/pedforQTLRel.txt", sep="\t", header=T)[1:5]
# ail.k <- kinship(ped=ail.ped, ids=geno.samples$id)
# save(ail.k, file="./pedigree/kinship.geno.samples.RData")

# no need to run the block of code above. just load what you need from:

load("./pedigree/info.phenoSamples.RData") # redundant info for phenotyped samples
load("./pedigree/geno.samples.RData") # genotyped sample IDs

pedigree <- read.table("./pedigree/pedforQTLRel.txt", sep="\t", header=T, as.is=T)[1:5]

load("./pedigree/ail.k.genotyped.RData") # ped kinship matrix
load("./pedigree/grm.geno.samples.RData") # grm


### For each mouse, list all animals that have a kinship value > 0.05
relatives<- c()
for (i in rownames(grm)){
    #if(length(which(grm[i,] > 0.05)) > 1){
    relatives[[i]] <- which(grm[i,] > 0.05)
    # }
}
# r <- names(relatives)
# r <- as.numeric(r) # get rid of decimals
# names(relatives) <- r
# colnames(k.geno) <- colnames(grm)

## scaled and centered values
k.geno.sc <- scale(k.geno)
# the grm generated by gemma is already centered.
grm.sc <- scale(grm, center=FALSE, scale=apply(grm, 2, sd, na.rm=T))
relatives2<- c()
for (i in rownames(grm.sc)){
    #if(length(which(grm[i,] > 0.05)) > 1){
    relatives2[[i]] <- which(grm.sc[i,] > 2.5)
    # }
}

###### FUNCTION: check.kinship generates a data frame for each element in ailrel,
# which is a list with the same structure as in relatives, above.

check.kinship <- function(ailrel, genok, pedk, pedigree){
# values will be a data frame with row.names = mouse ids, idx1 and 2 = index
# numbers in both the grm and ped matrices
values <- c()

for (name in seq_along(names(ailrel))){
    len <- length(ailrel[[name]])
    id.tmp <- as.numeric(names(ailrel)[name]) - 0.1
    id <- ailrel[[name]][[which(names(ailrel[[name]]) == id.tmp)]]
    values[[name]] <- data.frame(idx1=rep(id, times=len),
                                 idx2=ailrel[[name]])

    k_grm <- c() # column with grm kinship between idx 1 and 2
    k_ped <- c() # same as above but with values for ped kinship
    ped_kin <- c() # kin (relatives) with ped kinship > 0.48 for the mouse with idx2

        for (i in seq_along(values[[name]][['idx2']])){
           k_grm <- c(k_grm, genok[values[[name]][1,1], values[[name]][i,2] ])
           k_ped <- c(k_ped, pedk[values[[name]][1,1], values[[name]][i,2] ])
           ped_kin <-c(ped_kin, paste(names(which(pedk[values[[name]][i,2],] > 0.48)),
                            sep="", collapse=" "))
        }
    rownames(values[[name]]) <- as.integer(rownames(values[[name]]))+0.1

    values[[name]] <- cbind(values[[name]],
                            pedigree[pedigree$id %in% rownames(values[[name]]), c(2:5)])

    values[[name]][["k.grm"]] <- k_grm
    values[[name]][["k.ped"]] <- k_ped
    values[[name]][["ped.kin"]] <- ped_kin
}
names(values)<- names(ailrel)
return(values)
}



kinCheck.allgeno<- check.kinship(ailrel=relatives, genok=grm, pedk=k.geno, pedigree=pedigree)
save(kinCheck.allgeno, file="./pedigree/kinCheck.allgeno.RData")

kinCheck.allgenoScaled<- check.kinship(ailrel=relatives2, genok=grm.sc, pedk=k.geno.sc, pedigree=pedigree)
save(kinCheck.allgenoScaled, file="./pedigree/kinCheck.allgenoScaled.RData")



# collapse list
df<-c()
for(i in kinCheck.allgenoScaled){
    df <- rbind.data.frame(df,i)
}

df$dam <- as.factor(df$dam)
df$generation <- as.factor(df$generation)

write.table(df, "./pedigree/kinCheck.allgeno.txt", row.names=T, col.names=T,
            sep="\t", quote=F)
write.table(df, "./pedigree/kinCheck.allgenoScaled.txt", row.names=T, col.names=T,
            sep="\t", quote=F)

